# yaml-language-server: $schema=https://json-schema.axonivy.com/14.0-dev/config/custom-fields.json
# == Custom Fields Information ==
# 
# You can define here your project custom fields.
#
CustomFields:
