# yaml-language-server: $schema=https://json-schema.axonivy.com/14.0-dev/config/roles.json
Roles:
  - Id: CaseOwner
  - Id: HR
    Name: Human resources department
  - Id: TestRoleInvolved
    Name: TestRoleInvolved
  - Id: Sales
