# yaml-language-server: $schema=https://json-schema.axonivy.com/14.0-dev/config/users.json
Users:
  - Name: caseOwnerUser
    Password: caseOwnerUser
    Roles:
      - CaseOwner
  - Name: david
    Password: david
    FullName: david
    Roles:
      - HR
  - Name: peter
    Password: peter
    Roles:
      - HR
