# yaml-language-server: $schema=https://json-schema.axonivy.com/app/14.0.0/roles.json
Roles:
- Id: PortalSystem
  Name: Portal System
- Id: GeneralManager
  Name: General Manager
- Id: CostObject
  Name: Cost Object
