# yaml-language-server: $schema=https://json-schema.axonivy.com/app/14.0.0/users.json
Users:
  - Name: costObject1
    Password: costObject1
    FullName: Evan Cost Object
    Mail: axonivyportal+evan@gmail.com
    Roles:
      - CostObject
  - Name: costObject2
    Password: costObject2
    FullName: James Cost Object
    Mail: axonivyportal+james@gmail.com
    Roles:
      - CostObject
  - Name: gm1
    Password: gm1
    FullName: Martin Manager
    Mail: axonivyportal+martin@gmail.com
    Roles:
      - GeneralManager
  - Name: gm2
    Password: gm2
    FullName: Thomas Manager
    Mail: axonivyportal+thomas@gmail.com
    Roles:
      - GeneralManager
  - Name: gm3
    Password: gm3
    FullName: Sherley Manager
    Mail: axonivyportal+sherley@gmail.com
    Roles:
      - GeneralManager
      - CostObject
  - Name: huang
    Password: huang
    FullName: Huang Employee
    Mail: axonivyportal+huang@gmail.com
  - Name: marissa
    Password: marissa
    FullName: Marissa Accountant
    Mail: axonivyportal+marissa@gmail.com
  - Name: mike
    Password: mike
    FullName: Mike Approver
    Mail: axonivyportal+mike@gmail.com
  - Name: sophie
    Password: sophie
    FullName: Sophie Manager
    Mail: axonivyportal+sophie@gmail.com
  - Name: liam
    Password: liam
    FullName: Liam Developer
    Mail: axonivyportal+liam@gmail.com
  - Name: ava
    Password: ava
    FullName: Ava Designer
    Mail: axonivyportal+ava@gmail.com
  - Name: ethan
    Password: ethan
    FullName: Ethan Analyst
    Mail: axonivyportal+ethan@gmail.com
  - Name: emma
    Password: emma
    FullName: Emma Project Lead
    Mail: axonivyportal+emma@gmail.com
  - Name: olivia
    Password: olivia
    FullName: Olivia Consultant
    Mail: axonivyportal+olivia@gmail.com
  - Name: noah
    Password: noah
    FullName: Noah IT Support
    Mail: axonivyportal+noah@gmail.com
