# yaml-language-server: $schema=https://json-schema.axonivy.com/config/14.0.0/variables.json
# == Variables ==
# 
# You can define here your project Variables.
# If you want to define/override a Variable for a specific Environment, 
# please add a 'variables.yaml' in the sub directory '_<environment>'.
#
Variables:
